FROM osrf/ros:melodic-desktop

SHELL [ "/bin/bash" , "-c" ]

RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc

# Windows line uncomment for non-windows
RUN echo "LIBGL_ALWAYS_INDIRECT=0" >> ~/.bashrc

RUN source /opt/ros/melodic/setup.bash && \
sudo apt update && \
sudo apt install -y python3-catkin-pkg-modules python3-rospkg-modules python3-empy && \
mkdir -p ~/catkin_ws/src && \
cd ~/catkin_ws && \
catkin_make && \
echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc

#ENV PYTHONPATH=/root/catkin_ws/devel/lib/python3/dist-packages/:$PYTHONPATH

RUN apt-get install -y ros-$ROS_DISTRO-fetch-gazebo-demo

RUN sudo apt-get install vim -y
### conda install breaks fetch simulation, but not turtlesim
# RUN apt-get update && apt install -y wget && \
# wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

# ENV PATH=/opt/conda/bin:$PATH
# RUN bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
#     /opt/conda/bin/conda init bash && \
#     source ~/.bashrc && \
#     pip3 install rospkg numpy tensorflow tensorflow_hub matplotlib protobuf opencv-python

RUN sudo apt-get install net-tools

RUN echo "all done"