services:
  frontend:
    build: ./robot_dashboard.Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ..:/workspace
      - ~/.config/nvim:/root/.config/nvim
    working_dir: /workspace
