name: homebot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build frontend
      run: |
        cd robot-dashboard
        npm install
        nohup npm run dev > backend.log 2>&1 &

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
  
    - name: Pull backend image
      run: docker pull jaimec21/jazzy_pi:latest

    - name: Start backend container
      run: |
        docker run -d \
          --entrypoint tail \
          --init \
          --privileged \
          --net=host \
          --name ros2-container \
          -v ${{ github.workspace }}:/workspaces/homebot \
          jaimec21/jazzy_pi:latest \
          -f /dev/null

    - name: Debug container
      if: always()
      run: |
        docker ps -a
        docker logs ros2-container || true
        docker inspect ros2-container --format='Status={{.State.Status}} ExitCode={{.State.ExitCode}} Error={{.State.Error}}'

    - name: Build backend
      run: |
        docker exec ros2-container bash -c "
          cd /workspaces/homebot/ros2_ws
          colcon build
          source install/setup.bash
          "

    - name: Start backend
      run: |
        docker exec -d ros2-container bash -c "
          cd /workspaces/homebot/ros2_ws
          source /opt/ros/jazzy/setup.bash
          source install/setup.bash
          ros2 launch robot_control robot_move_launch.py
        "

    # Tests
    - name: Run tests
      run: |
        echo "Run your integration tests here"

    # Cleanup
    # - name: Stop backend container
    #   if: always()
    #   run: |
    #     docker stop homebot-backend
    #     docker rm homebot-backend


# to consider later maybe
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3